### RNG strategies

abstract type AbstractRNGStrategy end
struct HostSide <: AbstractRNGStrategy end
struct DeviceSide <: AbstractRNGStrategy end

"""
    _rng_strategy(::AbstractRNG)::AbstractRNGStrategy

"""
function _rng_strategy end

#_rng_strategy(::Xoshiro) = HostSide()
_rng_strategy(::Xoshiro) = DeviceSide()
_rng_strategy(::MersenneTwister) = HostSide()
_rng_strategy(::GPUArrays.RNG) = HostSide()

### backend specific rand functions
# these functions can be overwritten for different backends
function _rand_backend!(
        rng::R,
        ::HostSide,
        sampler::AbstractSampler{Ts, Tw},
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer,
    ) where {Ts, Tw, R <: Random.AbstractRNG}

    _rand_from_host!(rng, sampler, backend, buf)

    return nothing
end

function _rand_backend!(
        rng::R,
        ::DeviceSide,
        sampler::AbstractSampler,
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer
    ) where {R <: AbstractRNG}

    _rand_from_device!(rng, sampler, backend, buf)

    return nothing
end


### internal rand function
# can be overwritten for specific combinations of all inputs (especially combinations of
# rng and sampler)
@inline function _rand!(
        rng::Random.AbstractRNG,
        sampler::AbstractSampler,
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer
    )
    _rand_backend!(rng, _rng_strategy(rng), sampler, backend, buf)
    return nothing
end

### generic implementation which falls back to _rand_single
# NOTE: only works for device side rng and if _rand_single is implemented

@kernel function _rand_gpu_kernel(rng, sampler::AbstractSampler, buf::AbstractSampleBuffer)
    idx = @index(Global, Linear)
    sample = _rand_single(rng, sampler)
    setsample!(buf, sample, idx)
end

function _rand_from_device!(
        rng::AbstractRNG,
        sampler::AbstractSampler,
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer,
    )
    _rand_gpu_kernel(backend, 32)(
        rng, sampler, buf;
        ndrange = size(buf)
    )
    return nothing
end


### User-facing sampler API

"""
    rand_single(rng::AbstractRNG, sampler::AbstractSampler)::Sample

Generate a single sample from `sampler` using `rng`.

This function is the scalar sampling entry point. It is intended for use
cases where exactly one sample is required, including execution inside
device kernels.

The concrete sampling mechanism is determined by the sampler implementation
and the RNG type. In particular, samplers may require a device-compatible
RNG when `rand_single` is used in accelerator code.

See also: [`rand!`](@ref).
"""
@inline function rand_single(rng::AbstractRNG, sampler::AbstractSampler)
    return _rand_single(rng, sampler)
end

"""
    Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler,
        [backend::KernelAbstractions.Backend = get_backend(bug)],
        buf::AbstractSampleBuffer
    )::Nothing

Fill `buf` with samples generated by `sampler` using `rng` on the given
`backend`.

This is the primary bulk-sampling interface. The function generates as many samples as
required by `buf` and writes them in-place. The concrete execution strategy (host-side
RNG, or device-side RNG) is selected by the sampler implementation.

`buf` may reside on host or device memory, depending on the backend and
buffer type.
"""
@inline function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer
    ) where {Ts, Tw}

    _rand!(rng, sampler, backend, buf)
    return nothing
end

@inline function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        buf::AbstractSampleBuffer
    ) where {Ts, Tw}
    _rand!(rng, sampler, get_backend(buf), buf)
    return nothing
end
